# Generated by Django 4.0.1 on 2022-01-13 14:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(blank=True, default=api.models.create_new_ref_number, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('processing', 'processing'), ('click', 'click'), ('payme', 'payme'), ('cancelled', 'cancelled')], default='processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Cancelled', 'Cancelled'), ('Accepted', 'Accepted'), ('Finished', 'Finished')], default='Created', max_length=100),
        ),
    ]
